services:
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi_app/.env
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge